export const packagesData = [
  {
    id: 1,
    badge: "Silver",
    icon: "🌸",
    name: "Silver Wedding",
    desc: "Perfect for a simple, clean, and elegant wedding look.",
    features: [
      "Available for Punjabi & Hindu Weddings",
      "Special Groom Turban Styling",
      "Complete Wedding Day Styling",
      "Premium Quality Wedding Look",
      "Standard Safa Draping",
      "Clean & Professional Finishing",
      
      "Free travel up to 30KM (Charges apply after 30KM)",
      "Stay, food, and travel expenses are covered by the client",
    ],
    price: 4100,
    popular: false,
    theme: "silver",
    stepText: "Step 1: Essential Styling Coverage", 
  },
  {
    id: 2,
    badge: "Gold",
    icon: "👑",
    name: "Gold Royal",
    desc: "Premium multi-event styling for the groom and close family.",
    features: [
      "Available for Punjabi & Hindu Weddings",
      "Complete Groom Styling for All Functions",
      "Full Coverage for 2-3 Days Events",
      "Includes Styling for 5 Family Members",
      "Royal Safa Draping & Styling",
      "Coordinated Family Turban Look",
      "High-Quality Premium Finishing",
      
      "Free travel up to 30KM (Charges apply after 30KM)",
      "Stay, food, and travel expenses are covered by the client",
    ],
    price: 8500,
    popular: true,
    theme: "gold",
    stepText: "Step 2: Grand Multi-Event Upgrade", 
  },
  {
    id: 3,
    badge: "Platinum",
    icon: "💎",
    name: "Platinum Luxury",
    desc: "The ultimate luxury wedding experience with a dedicated personal stylist.",
    features: [
      "Available for Punjabi & Hindu Weddings",
      "Premium Styling for All Wedding Functions",
      "Exclusive Pre-Wedding Shoot Styling",
      "Full-Day Dedicated Stylist (Stay with Groom)",
      "Styling for Unlimited Family Members",
      "Premium Designer Royal Safa",
      "Special Luxury Fabric Draping",
      "Top-Tier VIP Luxury Finish",
      
      "Free travel up to 50KM (Charges apply after 50KM)",
      "Stay, food, and travel expenses are covered by the client",
    ],
    price: 25000,
    popular: false,
    theme: "platinum",
    stepText: "Step 3: Ultimate VIP Luxury Experience", 
  },
];
